repos:
-   repo: https://github.com/life4/flakehell
    rev: v.0.7.1
    hooks:
    -   id: flakehell
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        entry: isort --profile black
